//1666632746721
let styles = new Map();
styles.set(1,"Synthwave");
styles.set(2,"Ukiyoe");
styles.set(3,"No Style");
styles.set(4,"Steampunk");
styles.set(5,"Fantasy Art");
styles.set(6,"Vibrant");
styles.set(7,"HD");
styles.set(9,"Psychic");
styles.set(10,"Dark Fantasy");
styles.set(11,"Mystical");
styles.set(14,"Etching");
styles.set(16,"Wuhtercuhler");
styles.set(17,"Provenance");
styles.set(18,"Rose Gold");
styles.set(21,"Psychedelic");
styles.set(22,"Ghibli");
styles.set(28,"Melancholic");
styles.set(29,"Transitory");
styles.set(31,"Toasty");
styles.set(32,"Realistic");
styles.set(34,"Arcane");
styles.set(35,"Throwback");
styles.set(36,"Daydream");
styles.set(37,"Surreal");
styles.set(39,"Pandora");
styles.set(40,"Malevolent");
styles.set(41,"Street Art");
styles.set(44,"Meme");
styles.set(45,"Comic");
styles.set(47,"Line-Art");
styles.set(48,"Gouache");
styles.set(49,"Polygon");
styles.set(50,"Paint");
styles.set(52,"HDR");
styles.set(53,"Analogue");
styles.set(54,"Retro-Futurism");
styles.set(55,"Isometric");
styles.set(57,"Bad Trip");
styles.set(58,"Cartoonist");
let steps= new Map();
steps.set(0,0);
steps.set(1,21);
steps.set(2,21);
steps.set(3,21);
steps.set(4,21);
steps.set(5,21);
steps.set(6,21);
steps.set(7,21);
steps.set(8,0);
steps.set(9,0);
steps.set(10,0);
steps.set(11,0);
module.exports.steps=steps;

module.exports.default = styles;